spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drbk?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml